@url_base = http://localhost:5003/api/comentario
@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1lIjoiYWRtIiwiZXhwIjoxNzUwMTE5NzUyfQ.90_IN6Hg53JH96JnFh2MILH7P4s6dHIDAvVEeRrbK-4

### LISTAR COMENTÁRIOS
GET {{url_base}}/listar
Authorization: Bearer {{token}}

### CRIAR COMENTÁRIO
POST {{url_base}}/criar
Authorization: Bearer {{token}}
Content-Type: application/json

{
    "texto": "Bom!!",
    "ItemId" : 1
}

### DELETAR COMENTÁRIO
DELETE {{url_base}}/deletar/{id}
Authorization: Bearer {{token}}
